### ISSUE TITLE
[meta] Pipeline/dependency issues

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/job-runner#406]
_This is a redux of [an originating issue](https://github.com/opensafely-core/job-runner/issues/261) for readability; readers of _this_ issue should probably the originating issue in full, for context._

The current set of proposals, in priority/dependency order:

- [x] opensafely-core/job-runner#315
- [x] opensafely-core/job-runner#319
    - [x] opensafely-core/job-runner#155
    - [ ] opensafely-core/job-runner#180 (but probably not; see [this comment](https://github.com/opensafely-core/job-runner/issues/261#issuecomment-1102844782), and [this one](https://github.com/opensafely-core/job-runner/issues/261#issuecomment-1098296759))
- [x] opensafely-core/job-runner#320

People picking these up should move the individual tasks to "Doing" in regatta (or whatever replaces Regatta in the New World)

**Comment by lucyb** [comment]
@benbc move to a wider product backlog, not pipeline team

**Comment by benbc** [comment]
I've replaced this issue with [this item](https://docs.google.com/document/d/1CG3iII7r6sJ0auZ1HUIuiUZMoiAV8LgHHqdzQSbjlSs/edit#heading=h.ojnolgk2jn3t) on the backlog.
